version: '3.8'

services:
  cyberpunkgame:
    container_name: cyberpunkgamecontainer
    build: .
    image: mlebioda/cyberpunk-game
    platform: linux/arm64
    ports:
      - 8080:80
    expose:
      - 80
    networks:
      - internalnet
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - internalnet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - internalnet

networks:
  internalnet:  # Declare this as an external network
    driver: bridge