name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run workflow when pushing to 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [[ -z "$DOCKER_USERNAME" || -z "$DOCKER_PASSWORD" ]]; then
            echo "ERROR: Missing Docker credentials!"
            exit 1
          fi
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: docker build -t cyberpunkgame .

 # sonarcloud:
 #   needs: build  # Run SonarCloud only if the build job succeeds
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Checkout repository
 #       uses: actions/checkout@v4

#      - name: Run SonarCloud Scan in Docker
#        run: |
#          docker run --rm \
#            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
#            sonarsource/sonar-scanner-cli \
#            -Dsonar.projectKey=my_project_key \
#            -Dsonar.organization=my_organization \
#            -Dsonar.sources=. \
#            -Dsonar.host.url=https://sonarcloud.io \f
#            -Dsonar.language=cpp \
#            -Dsonar.sourceEncoding=UTF-8

#  push_to_main:
#    needs: sonarcloud
#    runs-on: ubuntu-latest
#    if: success()
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

#      - name: Merge dev into main
#        run: |
#          git config --global user.name "GitHub Actions"
#          git config --global user.email "actions@github.com"
#          git checkout main
#          git merge --no-ff dev -m "Auto-merge from dev to main"
#          git push origin main
